ALTER TABLE GYM
  ADD CONSTRAINT `fk_Area_name_GYM`
    FOREIGN KEY (`Area_name`)
    REFERENCES `AREA` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE GYM
  ADD CONSTRAINT `fk_Leader_ID_GYM`
    FOREIGN KEY (`Leader_ID`)
    REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE BATTLE
  ADD CONSTRAINT `fk_Gym_name_BATTLE`
    FOREIGN KEY (`Gym_name`)
    REFERENCES `GYM` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;


ALTER TABLE HAS
  ADD CONSTRAINT `fk_Ability_name_HAS`
    FOREIGN KEY (`Ability_name`)
    REFERENCES `ABILITY` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE HAS
  ADD CONSTRAINT `fk_Pokemon_name_HAS`
    FOREIGN KEY (`Pokemon_name`)
    REFERENCES `POKEMON` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE PKM_WILD
  ADD CONSTRAINT `fk_Area_name_WILD`
    FOREIGN KEY (Area_name)
    REFERENCES `AREA` (Name)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE PKM_WILD
  ADD CONSTRAINT `fk_Name_WILD`
    FOREIGN KEY (`Name`)
    REFERENCES `POKEMON` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE PKM_WILD
  ADD CONSTRAINT fk_Trainer_ID_WILD
FOREIGN KEY (Trainer_ID)
REFERENCES TRAINER (ID)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE PKM_OWNED
  ADD CONSTRAINT `fk_Name_OWNED`
    FOREIGN KEY (`Name`)
    REFERENCES `POKEMON` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE PKM_OWNED
  ADD CONSTRAINT `fk_Trainer_ID_OWNED`
FOREIGN KEY (`Trainer_ID`)
REFERENCES `TRAINER` (`ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE POKEMON_TYPE
  ADD CONSTRAINT `fk_Pkm_name_PKM_TYPE`
    FOREIGN KEY (`Pkm_name`)
    REFERENCES `POKEMON` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE TRAINER
  ADD CONSTRAINT `fk_Area_name_TRAINER`
    FOREIGN KEY (`Area_name`)
    REFERENCES `AREA` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE BATTLE
  ADD CONSTRAINT `fk_Trainer1_ID_BATTLE`
    FOREIGN KEY (`Trainer1_ID`)
    REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE BATTLE
  ADD CONSTRAINT `fk_Trainer2_ID_BATTLE`
    FOREIGN KEY (`Trainer2_ID`)
    REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

ALTER TABLE BATTLE
  ADD CONSTRAINT `fk_Winner_ID_BATTLE`
    FOREIGN KEY (`Winner_ID`)
    REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
