SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = `TRADITIONAL,ALLOW_INVALID_DATES`;

DROP TABLE IF EXISTS ABILITY;
CREATE TABLE IF NOT EXISTS ABILITY (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (Name)
);
CREATE UNIQUE INDEX Name_UNIQUE
  ON ABILITY (Name);

DROP TABLE IF EXISTS AREA;
CREATE TABLE IF NOT EXISTS AREA
(
  `Name`        VARCHAR(45) NOT NULL PRIMARY KEY,
  `Occupiable`  TINYINT(1)  NOT NULL,
  `Description` TEXT        NULL,
  CONSTRAINT `Name_UNIQUE` UNIQUE (`Name`)
);


DROP TABLE IF EXISTS BATTLE;
CREATE TABLE IF NOT EXISTS BATTLE
(
  `ID`          INT         NOT NULL,
  `Trainer1_ID` INT         NOT NULL,
  `Trainer2_ID` INT         NOT NULL,
  `Winner_ID`   INT         NULL,
  `Gym_name`    VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `Trainer1_ID`, `Trainer2_ID`)
);
CREATE INDEX Gym_name_idx
  ON `BATTLE` (`Gym_name`);
CREATE INDEX Trainer1_ID_idx
  ON `BATTLE` (`Trainer1_ID`);
CREATE INDEX Trainer2_ID_idx
  ON `BATTLE` (`Trainer2_ID`);
CREATE INDEX Winner_ID_idx
  ON `BATTLE` (`Winner_ID`);


DROP TABLE IF EXISTS GYM;
CREATE TABLE IF NOT EXISTS GYM
(
  `Name`      VARCHAR(45) NOT NULL PRIMARY KEY,
  `Area_name` VARCHAR(45) NOT NULL,
  `Leader_ID` INT         NULL
  #   CONSTRAINT fk_Area_name_GYM
  #     FOREIGN KEY (`Area_name`) REFERENCES AREA (`Name`),
  #   CONSTRAINT fk_Leader_ID_GYM
  #     FOREIGN KEY (`Leader_ID`) REFERENCES pokemondb.TRAINER (ID)
);
CREATE INDEX `Area_name_idx`
  ON GYM (`Area_name`);
CREATE INDEX `Leader_ID_idx`
  ON GYM (`Leader_ID`);

# ALTER TABLE BATTLE
#   ADD CONSTRAINT fk_Gym_name_BATTLE
#   FOREIGN KEY (Gym_name) REFERENCES GYM (Name);


DROP TABLE IF EXISTS HAS;
CREATE TABLE IF NOT EXISTS HAS
(
  `Pokemon_name` VARCHAR(45) NOT NULL,
  `Ability_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pokemon_name`, `Ability_name`)
  #   CONSTRAINT fk_Ability_name_HAS
  #     FOREIGN KEY (`Ability_name`) REFERENCES ABILITY (Name)
);
CREATE INDEX `Ability_name_idx`
  ON HAS (`Ability_name`);


DROP TABLE IF EXISTS PKM_OWNED;
CREATE TABLE IF NOT EXISTS PKM_OWNED
(
  `Name`       VARCHAR(45) NOT NULL,
  `Trainer_ID` INT         NOT NULL,
  `Nickname`   VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Trainer_ID`, `Nickname`)
);
CREATE INDEX `Name_idx`
  ON PKM_OWNED (`Name`);
CREATE INDEX `Trainer_ID_idx`
  ON PKM_OWNED (`Trainer_ID`);


DROP TABLE IF EXISTS PKM_WILD;
CREATE TABLE IF NOT EXISTS PKM_WILD
(
  `Date_time`      DATETIME    NOT NULL,
  `Name`           VARCHAR(45) NOT NULL,
  `Aggressiveness` INT         NULL,
  `Stamina`        INT         NULL,
  Area_name        VARCHAR(45) NOT NULL,
  `Trainer_ID`     INT         NULL,
  PRIMARY KEY (Date_time, Name)
  #   CONSTRAINT fk_Area_name_WILD
  #     FOREIGN KEY (Area_name) REFERENCES AREA (Name)
);
CREATE INDEX `fk_Area_name_idx`
  ON PKM_WILD (`Area_name`);
CREATE INDEX `Name_idx`
  ON PKM_WILD (`Name`);
CREATE INDEX `Trainer_ID_idx`
  ON PKM_WILD (`Trainer_ID`);


DROP TABLE IF EXISTS POKEMON;
CREATE TABLE IF NOT EXISTS POKEMON
(
  `Name`        VARCHAR(20) NOT NULL PRIMARY KEY,
  `Description` MEDIUMTEXT  NOT NULL,
  CONSTRAINT `Name_UNIQUE` UNIQUE (`Name`)
);

# ALTER TABLE HAS
#   ADD CONSTRAINT `fk_Pokemon_name_HAS`
#     FOREIGN KEY (`Pokemon_name`) REFERENCES POKEMON (`Name`);
#
# ALTER TABLE PKM_OWNED
#   ADD CONSTRAINT `fk_Name_OWNED`
#     FOREIGN KEY (`Name`) REFERENCES POKEMON (`Name`);
#
# ALTER TABLE PKM_WILD
#   ADD CONSTRAINT `fk_Name_WILD`
#     FOREIGN KEY (`Name`) REFERENCES POKEMON (`Name`);

DROP TABLE IF EXISTS POKEMON_TYPE;
CREATE TABLE IF NOT EXISTS POKEMON_TYPE
(
  `Pkm_name` VARCHAR(45) NOT NULL,
  `Type`     VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pkm_name`, `Type`)
  #   CONSTRAINT `fk_Pkm_name_PKM_TYPE`
  #     FOREIGN KEY (`Pkm_name`) REFERENCES POKEMON (`Name`)
);
CREATE INDEX `Name_idx`
  ON POKEMON_TYPE (`Pkm_name`);


DROP TABLE IF EXISTS TRAINER;
CREATE TABLE IF NOT EXISTS TRAINER
(
  `ID`        INT AUTO_INCREMENT PRIMARY KEY,
  `username`  VARCHAR(20) NOT NULL,
  `password`  VARCHAR(20) NOT NULL,
  `FName`     VARCHAR(45) NOT NULL,
  `LName`     VARCHAR(45) NOT NULL,
  `Area_name` VARCHAR(45) NOT NULL,
  CONSTRAINT `ID_UNIQUE` UNIQUE (`ID`),
  CONSTRAINT  `USERNAME_UNIQUE` UNIQUE (`username`)
  #   CONSTRAINT `fk_Area_name_TRAINER`
  #     FOREIGN KEY (`Area_name`) REFERENCES AREA (`Name`)
);
CREATE INDEX Area_name_idx
  ON TRAINER (`Area_name`);

#
# ALTER TABLE BATTLE
#   ADD CONSTRAINT fk_Trainer1_ID_BATTLE
# FOREIGN KEY (Trainer1_ID) REFERENCES TRAINER (ID);
# ALTER TABLE BATTLE
#   ADD CONSTRAINT fk_Trainer2_ID_BATTLE
# FOREIGN KEY (Trainer2_ID) REFERENCES TRAINER (ID);
# ALTER TABLE BATTLE
#   ADD CONSTRAINT fk_Winner_ID_BATTLE
# FOREIGN KEY (Winner_ID) REFERENCES TRAINER (ID);
# ALTER TABLE PKM_OWNED
#   ADD CONSTRAINT fk_Trainer_ID_OWNED
# FOREIGN KEY (Trainer_ID) REFERENCES TRAINER (ID);
# ALTER TABLE PKM_WILD
#   ADD CONSTRAINT fk_Trainer_ID_WILD
# FOREIGN KEY (Trainer_ID) REFERENCES TRAINER (ID);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
