-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 21:32:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `ABILITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABILITY`;
CREATE TABLE IF NOT EXISTS `ABILITY` (
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `AREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AREA`;
CREATE TABLE IF NOT EXISTS `AREA` (
  `Name`        VARCHAR(45) NOT NULL,
  `Occupiable`  TINYINT(1)  NOT NULL,
  `Description` TEXT        NULL DEFAULT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `TRAINER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TRAINER`;
CREATE TABLE IF NOT EXISTS `TRAINER` (
  `ID`        INT(11)     NOT NULL AUTO_INCREMENT,
  `username`  VARCHAR(20) NOT NULL,
  `password`  VARCHAR(20) NOT NULL,
  `FName`     VARCHAR(45) NOT NULL,
  `LName`     VARCHAR(45) NOT NULL,
  `Area_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `USERNAME_UNIQUE` (`username` ASC),
  INDEX `Area_name_idx` (`Area_name` ASC),
  CONSTRAINT `fk_Area_name_TRAINER`
  FOREIGN KEY (`Area_name`)
  REFERENCES `AREA` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 2
  DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `GYM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GYM`;
CREATE TABLE IF NOT EXISTS `GYM` (
  `Name`      VARCHAR(45) NOT NULL,
  `Area_name` VARCHAR(45) NOT NULL,
  `Leader_ID` INT(11)     NULL DEFAULT NULL,
  PRIMARY KEY (`Name`),
  INDEX `Area_name_idx` (`Area_name` ASC),
  INDEX `Leader_ID_idx` (`Leader_ID` ASC),
  CONSTRAINT `fk_Area_name_GYM`
  FOREIGN KEY (`Area_name`)
  REFERENCES `AREA` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Leader_ID_GYM`
  FOREIGN KEY (`Leader_ID`)
  REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `BATTLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BATTLE`;
CREATE TABLE IF NOT EXISTS `BATTLE` (
  `ID`          INT(11)     NOT NULL,
  `Trainer1_ID` INT(11)     NOT NULL,
  `Trainer2_ID` INT(11)     NOT NULL,
  `Gym_name`    VARCHAR(45) NOT NULL,
  `Winner`      INT(1)      NOT NULL,
  PRIMARY KEY (`ID`, `Trainer1_ID`, `Trainer2_ID`),
  INDEX `Gym_name_idx` (`Gym_name` ASC),
  INDEX `Trainer1_ID_idx` (`Trainer1_ID` ASC),
  INDEX `Trainer2_ID_idx` (`Trainer2_ID` ASC),
  CONSTRAINT `fk_Gym_name_BATTLE`
  FOREIGN KEY (`Gym_name`)
  REFERENCES `GYM` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trainer1_ID_BATTLE`
  FOREIGN KEY (`Trainer1_ID`)
  REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trainer2_ID_BATTLE`
  FOREIGN KEY (`Trainer2_ID`)
  REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `POKEMON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `POKEMON`;
CREATE TABLE IF NOT EXISTS `POKEMON` (
  `Name`        VARCHAR(20) NOT NULL,
  `Description` MEDIUMTEXT  NOT NULL,
  `Type`        VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Name`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `HAS_ABILITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HAS_ABILITY`;
CREATE TABLE IF NOT EXISTS `HAS_ABILITY` (
  `Pokemon_name` VARCHAR(45) NOT NULL,
  `Name`         VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Pokemon_name`, `Name`),
  CONSTRAINT `fk_Pokemon_name_HAS`
  FOREIGN KEY (`Pokemon_name`)
  REFERENCES `POKEMON` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `PKM_OWNED`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PKM_OWNED`;
CREATE TABLE IF NOT EXISTS `PKM_OWNED` (
  `Name`       VARCHAR(45) NOT NULL,
  `Trainer_ID` INT(11)     NOT NULL,
  `Nickname`   VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Name`, `Trainer_ID`, `Nickname`),
  INDEX `Name_idx` (`Name` ASC),
  INDEX `Trainer_ID_idx` (`Trainer_ID` ASC),
  CONSTRAINT `fk_Name_OWNED`
  FOREIGN KEY (`Name`)
  REFERENCES `POKEMON` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trainer_ID_OWNED`
  FOREIGN KEY (`Trainer_ID`)
  REFERENCES `TRAINER` (`ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `PKM_WILD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PKM_WILD`;
CREATE TABLE IF NOT EXISTS `PKM_WILD` (
  `Date_time`      DATETIME    NOT NULL,
  `Name`           VARCHAR(45) NOT NULL,
  `Aggressiveness` INT(11)     NULL DEFAULT NULL,
  `Stamina`        INT(11)     NULL DEFAULT NULL,
  `Area_name`      VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Date_time`, `Name`),
  INDEX `fk_Area_name_idx` (`Area_name` ASC),
  INDEX `Name_idx` (`Name` ASC),
  CONSTRAINT `fk_Area_name_WILD`
  FOREIGN KEY (`Area_name`)
  REFERENCES `AREA` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Name_WILD`
  FOREIGN KEY (`Name`)
  REFERENCES `POKEMON` (`Name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = latin1;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
